# cloud-config-repo
#配置中心
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sakura-maple/cloud-config-repo.git
          username: sakura-maple
          password: hanyu960822
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9991/eureka/
